import { TemplateSchema } from '../types/resume';

export const LAUNCH_TEMPLATES: TemplateSchema[] = [
  // Category 1: Minimalist / ATS-Strict (1-5)
  {
    templateId: 'clean-slate-01',
    name: 'Clean Slate',
    description: 'Single-column layout with zero distracting graphics. Maximum ATS parsing success rate.',
    category: 'Minimal',
    atsScore: 99,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'projects', 'skills', 'certifications'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#6366f1', spacingDensity: 'comfortable' },
    recommendedRoles: ['Software Engineer', 'Product Manager', 'Data Analyst'],
  },
  {
    templateId: 'pure-text-pro-02',
    name: 'Pure Text Pro',
    description: 'Plain-text optimized layout with strict structural hierarchy for conservative ATS systems.',
    category: 'Minimal',
    atsScore: 99,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'skills', 'projects'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#475569', spacingDensity: 'comfortable' },
    recommendedRoles: ['Compliance Specialist', 'Government Role', 'Operations Lead'],
  },
  {
    templateId: 'whitespace-03',
    name: 'Whitespace',
    description: 'Generous margins and subtle horizontal dividers creating an airy, readable aesthetic.',
    category: 'Minimal',
    atsScore: 97,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'education', 'skills'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#64748b', spacingDensity: 'spacious' },
    recommendedRoles: ['Product Designer', 'Frontend Engineer', 'Technical Writer'],
  },
  {
    templateId: 'classic-serif-04',
    name: 'Classic Serif',
    description: 'Traditional editorial layout using Georgia serif headings for high-trust executive roles.',
    category: 'Minimal',
    atsScore: 96,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'certifications', 'skills'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#1e293b', spacingDensity: 'comfortable' },
    recommendedRoles: ['Legal Counsel', 'Executive', 'Editor'],
  },
  {
    templateId: 'grid-line-05',
    name: 'Grid Line',
    description: 'Subtle horizontal accent lines delineating core section headers cleanly.',
    category: 'Minimal',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'skills', 'experience', 'education', 'projects'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#0f172a', spacingDensity: 'comfortable' },
    recommendedRoles: ['Architect', 'Systems Lead', 'Consultant'],
  },

  // Category 2: Modern / Tech & Startup (6-10)
  {
    templateId: 'vercel-edge-06',
    name: 'Vercel Edge',
    description: 'Monospace accent badges and crisp dark header styling inspired by modern dev platforms.',
    category: 'Tech',
    atsScore: 97,
    layout: 'header-banner',
    defaultSectionOrder: ['summary', 'skills', 'experience', 'projects', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#6366f1', spacingDensity: 'compact' },
    recommendedRoles: ['Full Stack Engineer', 'Cloud Architect', 'DevOps Specialist'],
  },
  {
    templateId: 'dev-console-07',
    name: 'Dev Console',
    description: 'Structured layout emphasizing technical stack tags and open-source contribution metrics.',
    category: 'Tech',
    atsScore: 96,
    layout: 'single-column',
    defaultSectionOrder: ['skills', 'experience', 'projects', 'education', 'summary'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#10b981', spacingDensity: 'compact' },
    recommendedRoles: ['Backend Engineer', 'Site Reliability Engineer', 'Security Lead'],
  },
  {
    templateId: 'terminal-mono-08',
    name: 'Terminal Mono',
    description: 'Full developer aesthetic with clean monospaced section headers.',
    category: 'Tech',
    atsScore: 95,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'skills', 'projects', 'experience', 'education'],
    defaultTheme: { fontFamily: 'Roboto', accentColor: '#06b6d4', spacingDensity: 'compact' },
    recommendedRoles: ['Infrastructure Engineer', 'Embedded Systems Developer'],
  },
  {
    templateId: 'gradient-header-09',
    name: 'Gradient Header',
    description: 'Features a subtle violet-to-cyan gradient banner for modern tech leaders.',
    category: 'Tech',
    atsScore: 94,
    layout: 'header-banner',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#8b5cf6', spacingDensity: 'comfortable' },
    recommendedRoles: ['Engineering Manager', 'Head of Product', 'Tech Lead'],
  },
  {
    templateId: 'minimal-sidebar-10',
    name: 'Minimal Sidebar',
    description: 'Left rail dedicated to key skills, GitHub links, and contact parameters.',
    category: 'Tech',
    atsScore: 95,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'education', 'skills'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#3b82f6', spacingDensity: 'comfortable' },
    recommendedRoles: ['Mobile Engineer', 'QA Architect', 'Data Engineer'],
  },

  // Category 3: Corporate / Executive (11-15)
  {
    templateId: 'boardroom-11',
    name: 'Boardroom',
    description: 'Navy blue accents paired with structured double rules for senior leadership.',
    category: 'Executive',
    atsScore: 95,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'certifications', 'skills'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#1e3a8a', spacingDensity: 'comfortable' },
    recommendedRoles: ['VP of Engineering', 'Chief Technology Officer', 'General Manager'],
  },
  {
    templateId: 'executive-brief-12',
    name: 'Executive Brief',
    description: 'Dense, metrics-forward layout highlighting multi-million dollar revenue impact.',
    category: 'Executive',
    atsScore: 96,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'skills', 'certifications'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#1e293b', spacingDensity: 'compact' },
    recommendedRoles: ['Managing Director', 'Chief Product Officer', 'Operations Director'],
  },
  {
    templateId: 'consultant-grid-13',
    name: 'Consultant Grid',
    description: 'Two-column structured layout for McKinsey / BCG style project case summaries.',
    category: 'Executive',
    atsScore: 94,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'education', 'skills'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#334155', spacingDensity: 'comfortable' },
    recommendedRoles: ['Strategy Consultant', 'Program Manager', 'Engagement Lead'],
  },
  {
    templateId: 'finance-pro-14',
    name: 'Finance Pro',
    description: 'Conservative, high information-density layout designed for Wall Street & banking.',
    category: 'Executive',
    atsScore: 97,
    layout: 'single-column',
    defaultSectionOrder: ['experience', 'education', 'skills', 'certifications', 'summary'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#0f172a', spacingDensity: 'compact' },
    recommendedRoles: ['Investment Banker', 'Financial Analyst', 'Portfolio Manager'],
  },
  {
    templateId: 'legal-formal-15',
    name: 'Legal Formal',
    description: 'Strict typographic hierarchy with zero color accents for formal legal submissions.',
    category: 'Executive',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'certifications', 'skills'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#000000', spacingDensity: 'comfortable' },
    recommendedRoles: ['Corporate Attorney', 'General Counsel', 'Regulatory Specialist'],
  },

  // Category 4: Creative (16-20)
  {
    templateId: 'bold-type-16',
    name: 'Bold Type',
    description: 'Large typographic name header with high-contrast section headers.',
    category: 'Creative',
    atsScore: 93,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#ec4899', spacingDensity: 'comfortable' },
    recommendedRoles: ['Art Director', 'Creative Strategist', 'Brand Lead'],
  },
  {
    templateId: 'color-block-17',
    name: 'Color Block',
    description: 'Soft pastel background blocks behind section titles for high visual punch.',
    category: 'Creative',
    atsScore: 92,
    layout: 'header-banner',
    defaultSectionOrder: ['summary', 'projects', 'experience', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#8b5cf6', spacingDensity: 'comfortable' },
    recommendedRoles: ['UI/UX Designer', 'Motion Designer', 'Product Marketer'],
  },
  {
    templateId: 'portfolio-edge-18',
    name: 'Portfolio Edge',
    description: 'Designed specifically to emphasize portfolio project links and interactive Dribbble/Figma showcases.',
    category: 'Creative',
    atsScore: 94,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'projects', 'skills', 'experience', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#06b6d4', spacingDensity: 'comfortable' },
    recommendedRoles: ['Design Systems Engineer', 'Product Designer', 'Frontend Specialist'],
  },
  {
    templateId: 'timeline-view-19',
    name: 'Timeline View',
    description: 'Subtle vertical timeline accent linking career milestones.',
    category: 'Creative',
    atsScore: 91,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'education', 'skills'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#f43f5e', spacingDensity: 'comfortable' },
    recommendedRoles: ['Growth Marketer', 'Content Lead', 'Design Lead'],
  },
  {
    templateId: 'circle-avatar-20',
    name: 'Circle Avatar Modern',
    description: 'Includes decorative header layout variant suitable for creative global applications.',
    category: 'Creative',
    atsScore: 90,
    layout: 'header-banner',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#f59e0b', spacingDensity: 'comfortable' },
    recommendedRoles: ['Creative Producer', 'Media Strategist', 'UI Specialist'],
  },

  // Category 5: Academic / Fresher / Campus (21-25)
  {
    templateId: 'fresh-grad-21',
    name: 'Fresh Grad',
    description: 'Prioritizes academic degree coursework, thesis projects, and GPA over work history.',
    category: 'Student',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['education', 'projects', 'skills', 'experience', 'certifications'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#10b981', spacingDensity: 'comfortable' },
    recommendedRoles: ['CS Graduate', 'New Grad Engineer', 'Research Assistant'],
  },
  {
    templateId: 'campus-leader-22',
    name: 'Campus Leader',
    description: 'Highlights university club leadership, hackathon awards, and campus involvement.',
    category: 'Student',
    atsScore: 97,
    layout: 'single-column',
    defaultSectionOrder: ['education', 'projects', 'experience', 'skills', 'certifications'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#6366f1', spacingDensity: 'comfortable' },
    recommendedRoles: ['Student Association Officer', 'Hackathon Lead', 'Junior PM'],
  },
  {
    templateId: 'research-cv-23',
    name: 'Research CV',
    description: 'Multi-page academic CV layout emphasizing research papers, publications, and grants.',
    category: 'Academic',
    atsScore: 97,
    layout: 'single-column',
    defaultSectionOrder: ['education', 'projects', 'summary', 'experience', 'certifications'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#1e3a8a', spacingDensity: 'spacious' },
    recommendedRoles: ['PhD Candidate', 'Research Scientist', 'Postdoc Researcher'],
  },
  {
    templateId: 'intern-ready-24',
    name: 'Intern Ready',
    description: 'Compact 1-page layout designed specifically for summer internship candidates.',
    category: 'Student',
    atsScore: 99,
    layout: 'single-column',
    defaultSectionOrder: ['education', 'skills', 'projects', 'experience'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#06b6d4', spacingDensity: 'compact' },
    recommendedRoles: ['Software Engineer Intern', 'Data Science Intern', 'Product Intern'],
  },
  {
    templateId: 'scholarship-edition-25',
    name: 'Scholarship Edition',
    description: 'Emphasizes academic honors, Dean\'s List awards, and fellowship merit.',
    category: 'Academic',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['education', 'summary', 'projects', 'skills', 'experience'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#f59e0b', spacingDensity: 'comfortable' },
    recommendedRoles: ['Scholarship Applicant', 'Graduate Fellow', 'Academic Scholar'],
  },

  // Category 6: Two-Column & Compact (26-30)
  {
    templateId: 'sidebar-skills-26',
    name: 'Sidebar Skills',
    description: 'Dedicated left rail displaying technical skill categories, languages, and certifications.',
    category: 'Tech',
    atsScore: 94,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'education', 'skills'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#6366f1', spacingDensity: 'comfortable' },
    recommendedRoles: ['Full Stack Developer', 'Cloud Engineer', 'Systems Admin'],
  },
  {
    templateId: 'dual-balance-27',
    name: 'Dual Balance',
    description: 'Symmetrical 50/50 split layout organizing experience alongside technical projects.',
    category: 'Executive',
    atsScore: 93,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#8b5cf6', spacingDensity: 'comfortable' },
    recommendedRoles: ['Solutions Architect', 'Technical Program Manager'],
  },
  {
    templateId: 'compact-one-pager-28',
    name: 'Compact One-Pager',
    description: 'Ultra-dense single page template packing 5+ years of experience onto 1 page cleanly.',
    category: 'Minimal',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'skills', 'projects', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#0f172a', spacingDensity: 'compact' },
    recommendedRoles: ['Senior Software Engineer', 'Product Lead', 'Engineering Architect'],
  },
  {
    templateId: 'infographic-skills-29',
    name: 'Infographic Accent',
    description: 'Features clean skill bar accents for visual-heavy job roles.',
    category: 'Creative',
    atsScore: 91,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#ec4899', spacingDensity: 'comfortable' },
    recommendedRoles: ['UX Specialist', 'Visual Designer', 'Digital Strategist'],
  },
  {
    templateId: 'photo-modern-30',
    name: 'Photo Modern',
    description: 'Two-column layout designed for European and international CV standards requiring profile photos.',
    category: 'Executive',
    atsScore: 90,
    layout: 'two-column-left',
    defaultSectionOrder: ['summary', 'experience', 'education', 'projects', 'skills'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#1e3a8a', spacingDensity: 'comfortable' },
    recommendedRoles: ['International Consultant', 'EU Tech Lead', 'Global Operations Director'],
  },

  // Category 7: Specialized (31-33)
  {
    templateId: 'federal-government-31',
    name: 'Federal Government Format',
    description: 'Comprehensive long-form layout following US federal resume standards.',
    category: 'Academic',
    atsScore: 98,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'experience', 'education', 'certifications', 'skills'],
    defaultTheme: { fontFamily: 'Georgia', accentColor: '#1e293b', spacingDensity: 'comfortable' },
    recommendedRoles: ['Federal Contractor', 'Government Analyst', 'Defense Engineer'],
  },
  {
    templateId: 'career-change-32',
    name: 'Career Switcher',
    description: 'Summary-led functional layout emphasizing transferable core skills over past titles.',
    category: 'Minimal',
    atsScore: 95,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'skills', 'projects', 'experience', 'education'],
    defaultTheme: { fontFamily: 'Inter', accentColor: '#6366f1', spacingDensity: 'comfortable' },
    recommendedRoles: ['Career Switcher', 'Bootcamp Graduate', 'Transitioning Veteran'],
  },
  {
    templateId: 'freelancer-contractor-33',
    name: 'Freelancer / Contractor',
    description: 'Project-based layout grouping achievements by client projects rather than traditional employers.',
    category: 'Tech',
    atsScore: 96,
    layout: 'single-column',
    defaultSectionOrder: ['summary', 'projects', 'skills', 'experience', 'education'],
    defaultTheme: { fontFamily: 'Plus Jakarta Sans', accentColor: '#10b981', spacingDensity: 'comfortable' },
    recommendedRoles: ['Freelance Engineer', 'Independent Consultant', 'Agency Contractor'],
  },
];
