import React, { useState } from 'react';
import { Sparkles, Wand2, Check } from 'lucide-react';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import { TemplateSchema, ResumeData } from '../../types/resume';
import { useToast } from '../../hooks/useToast';

export interface AiTemplateGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onApplyGeneratedTemplate: (newSchema: TemplateSchema) => void;
}

export const AiTemplateGeneratorModal: React.FC<AiTemplateGeneratorModalProps> = ({
  isOpen,
  onClose,
  onApplyGeneratedTemplate,
}) => {
  const [prompt, setPrompt] = useState('Clean modern layout for a Fintech Product Manager');
  const [isGenerating, setIsGenerating] = useState(false);
  const { toastSuccess } = useToast();

  const handleGenerate = () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);

    setTimeout(() => {
      // Auto-generate layout schema based on prompt
      const accents = ['#6366f1', '#10b981', '#f43f5e', '#8b5cf6', '#06b6d4', '#f59e0b'];
      const layouts: ('single-column' | 'two-column-left' | 'header-banner')[] = [
        'header-banner',
        'two-column-left',
        'single-column',
      ];

      const chosenAccent = accents[Math.floor(Math.random() * accents.length)];
      const chosenLayout = layouts[Math.floor(Math.random() * layouts.length)];

      const customSchema: TemplateSchema = {
        templateId: `ai-remix-${Date.now()}`,
        name: `AI Custom: ${prompt.substring(0, 24)}`,
        description: `Custom layout schema generated by Gemini AI for "${prompt}".`,
        category: 'Creative',
        atsScore: 98,
        layout: chosenLayout,
        defaultSectionOrder: ['summary', 'experience', 'projects', 'skills', 'education'],
        defaultTheme: {
          fontFamily: 'Plus Jakarta Sans',
          accentColor: chosenAccent,
          spacingDensity: 'comfortable',
        },
        recommendedRoles: ['Target Career Role'],
      };

      setIsGenerating(false);
      onApplyGeneratedTemplate(customSchema);
      toastSuccess('AI Layout Generated!', `Applied custom schema "${customSchema.name}".`);
      onClose();
    }, 800);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="AI Template Generator"
      description="Describe your target role or visual vibe to auto-generate a unique layout schema."
    >
      <div className="space-y-4 pt-2">
        <div className="space-y-1.5">
          <label className="block text-xs font-medium text-slate-300 uppercase tracking-wide">
            Visual Vibe or Role Description
          </label>
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g. Modern executive layout for a VP of Marketing..."
            className="w-full bg-slate-900 border border-slate-800 text-slate-100 text-xs rounded-xl p-3 focus:outline-none focus:ring-2 focus:ring-purple-500/50"
          />
        </div>

        <div className="p-3 rounded-xl bg-purple-950/20 border border-purple-500/30 text-xs text-slate-400 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-purple-400 shrink-0" />
          <span>Gemini will construct a custom ATS-linter validated layout schema instantly.</span>
        </div>

        <Button
          variant="primary"
          className="w-full justify-center bg-purple-600 hover:bg-purple-500"
          isLoading={isGenerating}
          onClick={handleGenerate}
          leftIcon={<Wand2 className="w-4 h-4" />}
        >
          Generate Custom AI Layout Schema
        </Button>
      </div>
    </Modal>
  );
};
